name: custom_marker_icon
description: A package to use local image, network image and icons as google_maps_flutter's marker icon.
version: 0.2.0
repository: https://github.com/abhishekduhoon/custom_marker_icon
issue_tracker: https://github.com/abhishekduhoon/custom_marker_icon/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^2.1.1
  google_maps_flutter: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

